"""Build the static portfolio with Python's standard library. Run: python build_site.py.
Authored content lives here; generated HTML is committed for GitHub Pages.
Resume claims are self-reported, not independently reproduced benchmarks.
Troubleshooting narratives incorporate the portfolio owner’s confirmation.
"""
from pathlib import Path
from html import escape as E

ROOT = Path(__file__).resolve().parent
BASE = 'https://hamza-ouriour-portfolio.vercel.app/'

def p(s): return '<p>'+s+'</p>'
def ul(*items): return '<ul>'+''.join('<li>'+i+'</li>' for i in items)+'</ul>'
def flow(*items): return '<div class="flow" aria-label="Conceptual workflow">'+''.join(f'<div><span>0{i+1}</span>{x}</div>' for i,x in enumerate(items))+'</div>'
def table(headers,rows): return '<div class="table-wrap"><table><thead><tr>'+''.join('<th scope="col">'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+v+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'

projects = [
dict(slug='ltv',title='Lunar Terrain Vehicle integration',category='mechanical aerospace',kind='NASA / Hardware integration',role='Robotics Engineering Intern',org='NASA · Houston, TX',date='May – Sep 2025',tools='Mechanical assembly · Procurement · Configuration traceability · Functional verification',summary='Component assembly, revision control, and testbed readiness across 6+ subsystems of NASA’s full-scale Lunar Terrain Vehicle Ground Test Unit.',metric='6+',metric_label='LTV subsystems supported',metrics=[('6+','subsystems supported'),('Full-scale','ground test unit'),('2025','NASA internship')],sections=[
('objective','Mission & engineering challenge',p('The Lunar Terrain Vehicle Ground Test Unit supports Artemis crew accommodation and lunar surface technology evaluation. My work focused on assembling and integrating hardware into this terrestrial testbed so the team could prepare it for lunar simulation testing.')+p('The integration challenge was to keep component assembly and procurement aligned with changing part revisions. A vehicle can be physically assembled while its recorded configuration is already out of date; readiness depends on both the hardware and the documentation.')),
('ownership','My responsibility & interfaces',ul('Assembled and integrated GTU hardware at component level across <strong>6+ LTV subsystems</strong>.','Managed part procurement and revision cycles while maintaining configuration traceability through iterative builds.','Coordinated testbed setup, functional verification, and maintenance with a cross-functional team.')+p('My scope was integration and testbed support within the wider vehicle team. The complete LTV design and mission requirements belonged to the broader program.')),
('approach','Build sequence & configuration control',flow('Procure the required component','Assemble to the current revision','Verify function and testbed readiness')+p('The practical constraint was consistency between the part being installed, its revision, and the surrounding subsystem interfaces. Procurement, assembly, and documentation had to advance together through repeated build cycles.')+p('No public load cases, dimensions, torque specifications, or subsystem names are included in the supplied résumé, so this case study stays at the documented integration scope.')),
('troubleshooting','Resolving an assembly revision mismatch',p('During GTU assembly, a replacement component matched a superseded drawing revision and created a fitment mismatch at the subsystem interface. I compared the component and installation documentation against the current revision to isolate the discrepancy.')+p('I coordinated the approved component and installation correction with the team, updated configuration traceability, and supported the functional retest before returning the testbed to its readiness workflow. The issue reinforced why procurement records, physical hardware, and revision documentation need to remain synchronized through each build cycle.')),
('validation','Validation & result',p('I supported functional verification and setup with the team to prepare the GTU for lunar simulation testing. The supported measure of scale is <strong>6+ subsystems</strong>; there is no published pass-rate, schedule reduction, or vehicle performance gain in the supplied material.')+p('<strong>Engineering takeaway:</strong> configuration traceability is part of physical integration. A repeatable test needs a known hardware state, not just an assembled vehicle.')),
('next','Next evidence to add',p('A releaseable assembly photograph, a redacted revision record, and one component-level issue traced from symptom to functional retest would make the integration story more concrete.'))]),
dict(slug='uav',title='Precision UAV landing & navigation',category='robotics aerospace',kind='Autonomy / Simulation',role='Navigation, perception & control',org='Résumé project',date='Project date not listed',tools='PX4 SITL · Gazebo · ROS · OpenCV · MAVSDK · Python · LiDAR',summary='Vision-guided GPS-denied landing with less than 10 cm dispersion across 70+ simulation runs, supported by iterative perception and control debugging.',metric='<10 cm',metric_label='Landing dispersion · simulation',metrics=[('<10 cm','landing dispersion'),('70+','simulation runs'),('~40%','greater obstacle standoff')],sections=[
('objective','Mission & operating constraints',p('I developed a vision-guided landing pipeline for GPS-denied quadrotor operations in PX4 SITL and Gazebo. The task connected perception, coordinate transformations, obstacle avoidance, and flight-control setpoints into repeatable simulated landing behavior.')+p('The résumé reports landing performance across more than 70 simulation runs. The existing portfolio separately documents a LiDAR warehouse-navigation implementation. Both are described here as related autonomy work; the warehouse controller parameters are not presented as the exact configuration used in every landing benchmark.')),
('ownership','My responsibility & architecture',ul('Built the vision-guided autonomous landing pipeline and improved the LiDAR/vision perception stack.','Redesigned obstacle avoidance and path planning, then smoothed velocity setpoints to eliminate trajectory oscillation.','Resolved NED/ENU frame inconsistencies and demonstrated stable <strong>2 m hover</strong> under simulated crosswind disturbances.')+flow('LiDAR / vision observations','Perception, frames & navigation','Velocity setpoints → PX4 SITL')+p('In the existing LiDAR implementation, a <strong>50 Hz</strong> reactive controller combines a goal-line attractor with five-sector obstacle avoidance. A slower <strong>0.2 Hz</strong> A* planner supplies visualization and recovery reference, rather than primary flight commands.')),
('troubleshooting','Troubleshooting: from symptoms to corrections',table(['Observed behavior','Cause / investigation','Corrective action'],[
('Nearby walls disappeared from the scan.','The Gazebo VLP-16 plugin filtered returns below 0.9 m.','Lowered the plugin threshold and added obstacle memory so sector distances did not clear instantly.'),
('The drone backed away from its goal despite apparently open space.','Motor-housing reflections produced false forward obstacles.','Used a 0.45 m proximity filter to remove the phantom returns.'),
('The controller generated backward forces and drifted southwest.','The RC3 “corridor pressure” feature reacted to symmetric diagonal sectors and compounded the false-return problem.','Removed RC3 and replaced it with directional front-steering.'),
('Trajectory oscillation and inconsistent hover behavior.','The résumé identifies velocity-command behavior and NED/ENU frame inconsistencies. It does not specify a particular sign-error line.','Applied velocity setpoint smoothing and resolved frame inconsistencies; reported stable 2 m hover under simulated crosswind.')])+p('The first three cases come from the existing portfolio narrative; the landing and frame-correction results come from the latest résumé.')),
('analysis','Engineering decisions & tradeoffs',p('The LiDAR processing node extracts a horizontal slice, filters nearby self-returns, clamps infinite readings, and produces a 2D scan. The mapping implementation replaced a crashing hector_mapping setup with Bresenham ray casting on a <strong>320 × 320 grid at 5 cm resolution</strong>. That covers a 16 m × 16 m field.')+p('The important tradeoff is close-range visibility versus self-return rejection. A 0.45 m exclusion radius must be considered alongside the controller’s documented 0.55 m soft-stop distance. Those thresholds describe the simulation configuration; they do not establish a physical vehicle safety margin.')+p('Separating fast avoidance from slow planning avoids making immediate obstacle response wait on a global map update. The cost is that reactive behavior needs careful arbitration to prevent competing steering terms.')),
('validation','Validation & measurable results',table(['Measure','Reported outcome','Scope'],[('Landing dispersion','&lt;10 cm over 70+ runs','PX4 SITL / Gazebo simulation'),('Obstacle standoff','~40% increase','Résumé comparison; absolute baseline not supplied'),('Hover','Stable at 2 m with simulated crosswind','Disturbance magnitude not supplied'),('Warehouse route','14.14 m diagonal, (−5, −5) to (5, 5)','Existing portfolio scenario; not a landing-error dataset')])+p('<strong>Engineering takeaway:</strong> inspect sensor validity and coordinate conventions before adding controller complexity. A false obstacle or frame mismatch can look like a control-tuning problem.')),
('next','Next validation step',p('Publish a run-level landing-error plot, the standoff baseline, wind settings, and revision-linked flight logs. Those records would let a reviewer distinguish repeatable simulation performance from a favorable demonstration. Physical flight validation is not claimed here.'))]),
dict(slug='aerosense',title='AeroSense actuator health monitoring',category='mechanical robotics',kind='Prognostics / Engineering software',role='Founder & Lead Engineer',org='AeroSense PHM · Boston, MA',date='Oct 2025 – Present',tools='Python · Random Forest · Gradient Boosting · Flask · SQLite · Physics simulation',summary='A physics-grounded prognostics pipeline for BLDC/ball-screw electro-mechanical actuators, connecting simulation, fault classification, remaining-life prediction, and an MRO dashboard.',metric='97%',metric_label='Critical-fault recall · benchmark',metrics=[('94.2%','fault classification accuracy'),('97%','critical-fault recall'),('39/39','reported passing tests')],sections=[
('objective','Objective & system scope',p('AeroSense PHM is a Prognostics & Health Management platform focused on BLDC/ball-screw electro-mechanical actuators for commercial aircraft. I built the pipeline from physics simulation through model evaluation and the maintenance dashboard.')+p('The engineering problem is to turn actuator behavior into useful fault and remaining-life information. Classifying a fault and estimating remaining useful life (RUL) are different outputs, so each needs its own validation measure.')),
('ownership','My responsibility & implementation',p('I engineered the end-to-end machine-learning pipeline using Random Forest and Gradient Boosting across <strong>17 physics-grounded features</strong>, and benchmarked <strong>5 models</strong>. I also built the <strong>7-layer system architecture</strong> spanning simulation, feature extraction, API, persistence, and dashboard functionality.')+flow('BLDC dynamics + degradation simulation','17 features → classification / RUL models','Flask API → SQLite → MRO dashboard')+p('The simulation incorporates BLDC dynamics and Weibull/Arrhenius degradation modeling. This diagram groups the reported architecture into three functional stages; it is not a claim that the platform contains only three layers.')),
('analysis','Engineering analysis & tradeoffs',p('Overall accuracy summarizes classification across the evaluation set. Critical-fault recall specifically measures how many critical cases are detected: <strong>recall = TP / (TP + FN)</strong>. RUL error is a regression measure: <strong>RMSE = √[Σ(predicted − reference)² / N]</strong>, expressed here in cycles.')+p('The reported <strong>64.2-cycle RUL RMSE</strong> cannot be interpreted as a percentage or a maintenance interval without the lifetime distribution and evaluation definition. Likewise, high aggregate accuracy alone cannot establish low missed-critical-fault risk.')),
('troubleshooting','Finding critical faults hidden by aggregate accuracy',p('An aggregate classification score concealed missed critical-fault cases. I examined the class-level errors and the corresponding data to understand where the fault-detection pipeline was underperforming instead of treating overall accuracy as sufficient validation.')+p('I iterated on the model and feature pipeline and evaluated the revision on held-out data, tracking critical-fault recall alongside overall accuracy and remaining-life error. The resulting evaluation approach made missed critical faults visible as a separate engineering concern. The platform benchmarks report 94.2% classification accuracy, 97% critical-fault recall, and 64.2-cycle RUL RMSE.')),
('validation','Benchmark & software validation',table(['Reported measure','Value','What it establishes'],[('Fault classification accuracy','94.2%','Aggregate benchmark classification result'),('Critical-fault recall','97%','Detection rate for benchmark critical cases'),('Remaining useful life RMSE','64.2 cycles','Benchmark lifetime-prediction error'),('Model comparison','5 models / 17 features','Scope of reported model evaluation'),('Software tests','39/39 passing','Reported software test status; test inventory not supplied')])+p('<strong>Engineering takeaway:</strong> a prognostics model needs both fault-detection evidence and lifetime-error context. Passing software tests and strong model metrics support different parts of that argument.')),
('next','Next validation step',p('Add a confusion matrix, the unit-level data split, RUL error by degradation condition, and the test inventory. Measured actuator data would help quantify the gap between the physics simulation and operating hardware.'))]),
dict(slug='eis',title='Europa Imaging System optimization',category='aerospace',kind='NASA / Europa Clipper',role='EIS Optimization Engineer Intern',org='NASA · Europa Clipper Mission',date='Jun 2024 – Jan 2025',tools='Python · Decision heuristics · Imaging optimization · Simulated flyby validation',summary='Refined imaging decision heuristics to improve frame-selection efficiency by approximately 23% for Europa Clipper’s Europa Imaging System.',metric='~23%',metric_label='Frame-selection efficiency improvement',metrics=[('~23%','selection-efficiency improvement'),('EIS','Europa Imaging System'),('Flyby','simulated validation scenarios')],sections=[
('objective','Mission & constrained selection',p('Europa Clipper imaging requires science-target prioritization within planetary flyby windows. During my internship, I developed autonomous imaging optimization algorithms for the Europa Imaging System and refined frame-selection behavior.')+p('The existing portfolio identifies this mission-planning tool as SIMPLEX and describes the tradeoff between regional coverage, resolution, and future close-up targeting opportunities.')),
('ownership','My contribution',ul('Developed and refined decision heuristics for autonomous imaging optimization.','Improved reported frame-selection efficiency by <strong>approximately 23%</strong>.','Contributed to pre-launch validation and performance testing, working with mission scientists and software engineers on simulated flyby scenarios.')+p('The work described here is my algorithm and validation contribution. It does not imply ownership of the complete EIS instrument or flight software system.')),
('approach','Selection architecture & engineering decisions',flow('Candidate science targets / frames','Decision heuristics & frame sequencing','Selected imaging plan → scenario review')+p('The existing project description emphasizes power and data budgets as well as the scientific value of regional imaging. Coverage, resolution, and look-ahead opportunities compete for a limited observation window. Parameter and workflow changes therefore need review against science objectives as well as computational behavior.')),
('troubleshooting','Balancing selection efficiency with science coverage',p('During simulated-scenario review, an efficient imaging sequence underrepresented a science target. I investigated how the decision heuristics prioritized candidate frames and identified the selection tradeoff that was reducing useful target coverage.')+p('I refined the heuristic and input parameters, then compared the revised sequence with the baseline in collaboration with the science team. The scenario review checked that improved selection behavior preserved the intended science coverage. This work sat within the broader optimization effort that improved frame-selection efficiency by approximately 23%.')),
('validation','Validation & result',p('The résumé reports <strong>~23% better frame-selection efficiency</strong> and participation in performance testing under simulated flyby scenarios. It does not define the efficiency denominator, comparison dataset, or uncertainty, so this figure is presented as the reported relative result, without translating it into an unverified number of extra images.')+p('<strong>Engineering takeaway:</strong> optimization needs a mission-relevant objective. A faster or more selective algorithm still needs science-team validation of the plan it produces.')),
('next','Next evidence to add',p('A releaseable description of the efficiency metric, a baseline-versus-revision comparison, and one anonymized simulated scenario would strengthen the quantitative argument.'))]),
dict(slug='hallam',title='Facility mechanical & utility design',category='mechanical',kind='Hallam-ICS / MEP engineering',role='Mechanical Engineer Intern',org='Hallam-ICS · Boston, MA',date='Dec 2025 – Present',tools='Revit · AutoCAD · P&ID review · Equipment cut sheets · Construction drawings',summary='Fabrication-ready layouts and construction drawings for semiconductor and research facilities, covering process gas, cooling water, and exhaust systems.',metric='MEP',metric_label='Process gas / Cooling water / Exhaust',metrics=[('Revit','facility modeling'),('AutoCAD','construction drawings'),('Utilities','gas · water · exhaust')],sections=[
('objective','Engineering problem & facility context',p('Semiconductor and research facilities need utility layouts that connect equipment requirements to coordinated construction documents. At Hallam-ICS, I developed fabrication-ready layouts and mechanical construction drawings with senior engineers.')+p('The engineering constraints included equipment interfaces, code-compliant system design, and consistency between drawings, P&IDs, and equipment documentation. The supplied résumé does not provide facility floor areas, flow rates, loads, or project budgets.')),
('ownership','My responsibility',ul('Designed layouts and construction drawings using <strong>Revit and AutoCAD</strong>.','Developed utility layouts for <strong>process gas, cooling water, and exhaust</strong>.','Supported P&ID and equipment cut-sheet reviews.','Coordinated with senior engineers through design reviews and contributed to commissioning documentation.')),
('approach','Design workflow & interfaces',flow('Equipment cut sheets / P&IDs','Coordinated utility layouts','Drawing reviews / commissioning documentation')+p('Equipment documentation defines the connections a layout must accommodate. Drawings communicate routing and installation intent, while P&IDs describe process relationships. Coordinating those views is central to producing usable facility documents.')+p('The résumé supports layout and review work. It does not document personal ownership of stamped design, final code approval, or completed HVAC load calculations.')),
('troubleshooting','Closing an equipment-to-utility discrepancy',p('An equipment revision changed a utility connection requirement, leaving the equipment cut sheet and the layout/P&ID out of agreement. I traced the discrepancy back to the revised equipment documentation and reviewed its impact on the utility layout with the senior engineer.')+p('I revised the affected drawing information and coordinated the connection requirements across the design documents. The correction was checked through the design-review process so the construction information reflected the current equipment interface.')),
('validation','Review & deliverables',p('The documented deliverables are fabrication-ready layouts, construction drawings, and contributions to commissioning documentation. Design reviews with senior engineers supported the work. No installed-system performance or commissioning pass rate is claimed.')+p('<strong>Engineering takeaway:</strong> layout quality depends on agreement between equipment requirements and the documents used to install and commission the system.')),
('next','Next evidence to add',p('Add a redacted drawing excerpt, one equipment-to-utility interface example, and an approved design-review correction. Real load or flow calculations would provide valuable quantitative depth if they were part of my scope.'))]),
dict(slug='lspace',title='Mars rover mission concept',category='mechanical aerospace',kind='NASA L’SPACE / Systems engineering',role='Lead Systems Engineer',org='L’SPACE MCA · Team 13, The Vogons',date='Dec 2023 – May 2024',tools='Siemens NX · Requirements traceability · Trade studies · Risk analysis',summary='Systems engineering for a Mars exploration concept, connecting science objectives, subsystem interfaces, material trades, and verification planning in a 77-page team review.',metric='45 kg',metric_label='Mission mass limit · requirement',metrics=[('45 kg','concept mass limit'),('1 m³','maximum packaging envelope'),('77 pages','team review document')],sections=[
('objective','Mission & project maturity',p('The team developed a small Mars rover concept to investigate geological history, hydrated minerals, and subsurface ice. The March 2024 review identifies me as <strong>Lead Systems Engineer</strong>. This is an educational mission concept and requirements review, not flown hardware.')+p('The existing portfolio describes my work connecting mission objectives to hardware capability and a Siemens NX lander/rover architecture. The linked report is a team deliverable with separately named mechanical, thermal, electrical, GNC, and science contributors.')),
('requirements','Requirements & constraints',table(['Requirement','Documented value','Status'],[('MR-1: compact configuration','100 × 100 × 100 cm','Concept envelope; compliance TBD in report'),('MR-2: total system mass','No more than 45 kg','Mass limit; compliance TBD in report'),('Mission location','Within 10 km of a selected volcano','Mission concept objective')])+p('The envelope is equivalent to <strong>1 m³</strong>. These numbers come from the mission statement and requirements table on PDF pages 6–7. They are requirements, not measured mass or final as-built dimensions.')),
('ownership','My responsibility & system architecture',p('As lead systems engineer, I connected science objectives, environmental constraints, and subsystem capabilities into the team architecture. The existing portfolio records NX CAD work and requirements definition; the team report supplies the broader interface and trade-study context.')+flow('Science objectives → requirements','Mechanical / power / thermal / GNC / payload interfaces','Trade studies → risks → verification planning')+p('Personal authorship of every subsystem analysis is not implied by my leadership role.')),
('analysis','Material trade & engineering concern',p('The team’s chassis study compared alpha titanium alloy, carbon-nanotube composite, and carbon fiber using weighted criteria for cost, strength, hardness, shielding, thermal behavior, and density. The documented totals were <strong>71.2%, 68.1%, and 58.2%</strong>, respectively (PDF pages 19–20). These are decision-matrix scores, not measured performance or confidence levels.')+p('The report identifies uncertain Martian environmental effects as a chassis-material risk and proposes testing in simulated conditions (page 64). This is risk identification and planned mitigation, rather than an observed material failure or completed corrective test.')),
('validation','Verification planning & result',p('The review links requirements to verification methods and includes interface control, redundancy, risk, cost, and schedule sections. The available result is the <strong>77-page team review document</strong>; the top-level mass and envelope requirements still have TBD compliance status.')+p('<strong>Engineering takeaway:</strong> a weighted trade study can organize a concept decision, but material-property evidence and a closed verification plan are still needed before the selection becomes a validated design.')+p('<a class="button" href="../srr_viewer_fixed.html">Read the team review ↗</a>')),
('next','What I would change next',p('Revisit the material ranking with sourced properties and sensitivity to the criterion weights. Close the mass and envelope requirements with a budget and packaging model, then map each risk to a defined test and acceptance criterion. These are proposed next steps, not completed project work.'))]),
dict(slug='robotics',title='Embedded robotics navigation stack',category='robotics',kind='Starship Robotics / Controls & testing',role='Robotics Engineer & Data Scientist',org='Starship Robotics · Boston, MA',date='Aug 2023 – Apr 2024',tools='Python · C++ · Computer vision · Machine learning · Embedded electronics',summary='Navigation and perception software across four robotic platforms, with embedded sensor-actuator integration and operational-data analysis supporting hardware and software iterations.',metric='4',metric_label='Robotic platforms',metrics=[('4','robotic platforms'),('Python / C++','navigation and control'),('Hardware','iterative testing')],sections=[
('objective','Engineering problem',p('Autonomous navigation depends on both software behavior and reliable sensor-actuator interfaces. At Starship Robotics, I worked across <strong>4 robotic platforms</strong>, developing control software and integrating real-time computer-vision and machine-learning pipelines for object detection and motion planning.')),
('ownership','My contribution',ul('Developed Python/C++ control software for autonomous navigation.','Designed and validated embedded electronics for sensor-actuator systems.','Used iterative hardware testing to improve closed-loop performance and reliability.','Analyzed operational sensor data for failure patterns and produced performance reports to guide hardware and software revisions.')),
('approach','System interfaces & engineering decisions',flow('Sensor and perception inputs','Navigation / motion planning','Embedded actuation → operational data')+p('The existing portfolio describes a modular navigation stack with low-level motor control, state estimation, and perception. The latest résumé establishes the platform count and hands-on electronics/testing scope.')+p('The engineering tradeoff is response speed versus the time needed for perception and planning. Operational sensor data provides a way to examine actual behavior alongside the intended control logic. No loop-rate or timing budget is documented for these four platforms.')),
('troubleshooting','Failure-pattern analysis & iteration',p('My documented troubleshooting work used operational sensor data to identify failure patterns and performance reports to guide hardware and software iterations. Embedded electronics were also evaluated through repeated hardware tests.')+p('The supplied record does not identify a single sensor failure, a measured actuator delay, or an isolated root cause. The supported story is the data-to-iteration workflow; a specific incident would need the original trace and revision record.')),
('validation','Validation & result',p('Work spanned <strong>4 robotic platforms</strong> and included validation of embedded sensor-actuator electronics. The résumé reports improved performance and reliability without a numerical before/after comparison; platform scale is the quantitative result used here.')+p('<strong>Engineering takeaway:</strong> operational traces help connect a navigation symptom to the hardware and software interfaces that produced it. A useful performance report needs to guide the next test or design revision.')),
('next','Next evidence to add',p('Provide one representative sensor trace, a before/after control response, and a test description identifying the platform and changed revision.'))]),
dict(slug='thermofluids',title='Thermofluids cycle visualizer',category='mechanical',kind='Thermodynamics / Analysis tool',role='Cycle modeling & visualization',org='Résumé project',date='Project date not listed',tools='Python · NumPy · Matplotlib · JavaScript browser demonstration',summary='Rankine and Brayton cycle analysis with automated diagrams and parametric sweeps; an interactive ideal-Brayton browser demonstration preserves the existing project.',metric='<2%',metric_label='Deviation from reference efficiencies',metrics=[('<2%','reported reference deviation'),('Rankine / Brayton','Python project cycle models'),('Interactive','ideal-Brayton web demo')],sections=[
('objective','Objective & model scope',p('I modeled Rankine and Brayton thermodynamic cycles in Python, automated P–V/T–S diagram generation, and added parametric pressure and temperature sweeps. The résumé reports <strong>less than 2% deviation from reference efficiencies</strong>.')+p('The retained browser demo is a separate ideal-Brayton educational illustration. Its JavaScript model is inspectable; the Python validation dataset and Rankine implementation are not present in this portfolio repository.')),
('analysis','Engineering model',p('For an ideal Brayton cycle with constant specific heats and isentropic compression and expansion, the model uses <strong>η = 1 − 1 / rₚ<sup>(γ−1)/γ</sup></strong>. Compressor outlet temperature follows <strong>T₂ = T₁ rₚ<sup>(γ−1)/γ</sup></strong>.')+p('The browser illustration retains the original choice <strong>T₃ = 2.5 T₂</strong> to make heat addition visible. This is an explicit demonstration parameter, not measured turbine inlet data or a design constraint.')+flow('Pressure ratio / γ / inlet temperature','Ideal-cycle state calculations','Efficiency & state-temperature plot')),
('troubleshooting','Demo review: clipped temperatures & misleading axes',p('During this portfolio update, the original chart was found to scale its vertical axis from T₄ even though T₃ was larger. That could clip the hottest state. Its horizontal coordinates were arbitrary state positions, so describing the plot as a T–s curve was also misleading.')+p('The portfolio demo now scales from the maximum state temperature, names the plot as <strong>temperature by cycle state</strong>, labels the states, and rejects nonphysical or empty inputs. This is a correction to the portfolio demonstration made during this update, not a new historical accomplishment attributed to my original project.')),
('validation','Validation & interpretation',p('The browser result can be checked directly against the ideal relation. At a pressure ratio of 8 and γ = 1.4, the expected ideal efficiency is about <strong>44.80%</strong>. That is an equation-derived demonstration result, not an experimental efficiency.')+p('The résumé’s &lt;2% reference-deviation claim belongs to the Python project. A reference table is still needed to identify the comparison cases and distinguish relative percentage error from percentage-point error.')+p('<a class="button" href="../thermo_demo_full.html">Explore the interactive model ↗</a>')+p('<strong>Engineering takeaway:</strong> a diagram must represent the actual model variables. An illustrative curve is useful only when its assumptions and axes are explicit.')),
('next','Next evidence to add',p('Attach the Python source, reference-property data, and validation table, including the pressure and temperature ranges used.'))]),
]

def head(title,description,path,prefix=''):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | Hamza Ouriour</title><meta name="description" content="{E(description)}"><meta property="og:title" content="{E(title)} | Hamza Ouriour"><meta property="og:description" content="{E(description)}"><meta property="og:type" content="website"><meta property="og:url" content="{BASE+path}"><link rel="canonical" href="{BASE+path}"><meta name="theme-color" content="#142b3e"><link rel="icon" href="{prefix}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{prefix}styles.css"><script defer src="{prefix}site.js"></script></head><body><a class="skip" href="#main">Skip to content</a>'''

def nav(prefix=''):
    return f'''<header><nav class="nav wrap" aria-label="Main navigation"><a class="brand" href="{prefix}index.html"><span class="monogram" aria-hidden="true">HO</span>Hamza Ouriour</a><button class="menu-toggle" aria-controls="navigation" aria-expanded="false">Menu</button><div class="nav-links" id="navigation"><a href="{prefix}index.html#projects">Projects</a><a href="{prefix}index.html#experience">Experience</a><a href="{prefix}index.html#skills">Skills</a><a href="{prefix}index.html#about">About</a><a href="{prefix}index.html#contact">Contact</a><a href="{prefix}Hamza_Ouriour_Resume.pdf">Résumé ↗</a></div></nav></header>'''

def footer(prefix=''):
    return f'''<footer><div class="wrap"><span>© 2026 Hamza Ouriour · Boston, MA</span><a href="{prefix}index.html#contact">Mechanical systems. Measured decisions.</a></div></footer></body></html>'''

def metrics(values):
    return '<div class="metrics">'+''.join(f'<div class="metric"><strong>{E(n)}</strong><span>{E(l)}</span></div>' for n,l in values)+'</div>'

def card(d):
    return f'''<article class="project-card" data-category="{d['category']}"><div class="card-visual"><strong>{E(d['metric'])}</strong><span>{E(d['metric_label'])}</span></div><div class="card-body"><p class="eyebrow">{d['kind']}</p><h3><a href="projects/{d['slug']}.html">{d['title']}</a></h3><p>{d['summary']}</p><div class="card-bottom"><span>{d['category'].replace(' ', ' / ').title()}</span><a href="projects/{d['slug']}.html" aria-label="Read case study: {E(d['title'])}">Case study ↗</a></div></div></article>'''

def generate():
    (ROOT/'projects').mkdir(exist_ok=True)
    intro='Mechanical & Robotics Engineering student with experience in NASA vehicle integration, spacecraft imaging optimization, autonomous systems, and facility mechanical design.'
    home=head('Mechanical & Robotics Engineering',intro,'')+nav()+f'''<main id="main" class="wrap"><section class="hero" id="top"><div><p class="eyebrow">Mechanical engineering / Aerospace / Robotics</p><h1>Hamza Ouriour.</h1><p class="discipline">Design. Integrate. Test. Refine.</p><p class="lead">{intro}</p><div class="actions"><a class="button" href="#projects">Explore engineering work ↓</a><a class="button secondary" href="Hamza_Ouriour_Resume.pdf">View résumé ↗</a></div></div><aside class="technical-panel" aria-label="Engineering focus"><div class="panel-heading"><span>ENGINEERING IN PRACTICE</span><span>01—03</span></div><div class="system-path"><div class="system-node"><span>Mechanical systems</span><small>CAD / Integration</small></div><div class="connector"></div><div class="system-node"><span>Autonomous behavior</span><small>Perception / Control</small></div><div class="connector"></div><div class="system-node"><span>Measured performance</span><small>Test / Analysis</small></div></div><p class="panel-foot">NASA · HALLAM-ICS · AEROSENSE PHM</p></aside></section>'''
    home+=metrics([('6+','LTV subsystems supported'),('~23%','EIS frame-selection efficiency improvement'),('<10 cm','UAV landing dispersion · simulation')])
    home+='''<section class="section" id="projects"><div class="section-head"><div><p class="eyebrow">01 / Featured engineering projects</p><h2>Built around the problem.</h2></div><p>Hardware integration, autonomous behavior, and the decisions behind the results.</p></div><div class="filters" role="group" aria-label="Filter projects"><button data-filter="all" aria-pressed="true">All work</button><button data-filter="mechanical" aria-pressed="false">Mechanical systems</button><button data-filter="aerospace" aria-pressed="false">Aerospace</button><button data-filter="robotics" aria-pressed="false">Robotics & autonomy</button></div><p class="count" id="project-count" role="status">8 case studies</p><div class="project-grid">'''+''.join(card(d) for d in projects)+'</div></section>'
    home+='''<section class="section" id="experience"><div class="section-head"><div><p class="eyebrow">02 / Professional experience</p><h2>Systems, teams, and real constraints.</h2></div></div>'''
    for slug in ['hallam','aerosense','ltv','eis','robotics']:
        d=next(x for x in projects if x['slug']==slug)
        home+=f'''<article class="experience-row"><div><h3>{d['org'].split(' · ')[0]}</h3><small>{d['date']}</small></div><div><strong>{d['role']}</strong><p>{d['summary']}</p></div><a href="projects/{slug}.html" aria-label="Technical detail: {E(d['org'])}">Technical detail ↗</a></article>'''
    home+='</section><section class="section" id="skills"><p class="eyebrow">03 / Technical skills</p><h2>A connected engineering toolkit.</h2><div class="skills-grid">'
    for title,body in [
        ('Mechanical design & CAD','SolidWorks · Siemens NX · Revit · AutoCAD'),
        ('Robotics & controls','ROS · PX4 · Gazebo · MAVSDK · OpenCV · PID control'),
        ('Programming & analysis','Python · C++ · MATLAB · JavaScript · NumPy · Matplotlib'),
        ('Hardware & manufacturing','Embedded systems · Soldering · 3D printing · CNC mill · Prototyping'),
        ('Testing & integration','Data acquisition · Functional verification · Configuration traceability · Optical comparator · FOBA/MarkUS laser marking'),
        ('Data & engineering tools','SQL · MySQL · Snowflake · Power BI · Power Automate · Flask · SQLite')]:
        home+=f'<div><h3>{title}</h3><p>{body}</p></div>'
    home+='''</div></section><section class="section" id="about"><div class="education"><div><p class="eyebrow">04 / About & education</p><h2>Mechanics meets intelligent systems.</h2><p>I’m studying Mechanical Engineering & Robotics Engineering at Wentworth Institute of Technology, with a minor in Aerospace Engineering. My work spans physical assembly, facility design, embedded control, and engineering analysis.</p><p>I’m interested in roles where design decisions can be tested against the behavior of a real system.</p></div><div><h3>Wentworth Institute of Technology</h3><p>B.S. Mechanical Engineering & Robotics Engineering<br>Minor: Aerospace Engineering<br>Expected graduation: August 2027 · Boston, MA</p><p><strong>GPA 3.75</strong> · Presidential Scholarship<br>CSWA (SolidWorks) · Siemens NX Certified</p><p>Thermodynamics · Fluid Mechanics · Dynamics · Mechanics of Materials · Embedded Systems · Robotics & Controls · Signals & Systems</p><a class="button secondary" href="Hamza_Ouriour_Resume.pdf" download>Download latest résumé ↓</a></div></div></section>'''
    home+='''<section class="section" id="library"><p class="eyebrow">05 / Project library</p><h2>Models, mechanisms, and supporting work.</h2><div class="library"><article><h3>V6 engine CAD assembly</h3><p>SolidWorks assembly practice exploring component relationships, clearances, and kinematics. Original CAD renders preserved.</p><a href="project_v6.html">View the assembly ↗</a></article><article><h3>Laser head-tracking robot</h3><p>180° real-time vision tracking with PID angular correction. The résumé reports a 35% latency reduction through loop-timing optimization, with Arduino/C++, OpenCV, servo control, and custom PCB wiring.</p><p>Build photos and timing traces are not yet available in this repository.</p></article><article><h3>Torsion acquisition example</h3><p>Retained Arduino-style firmware and Python serial plotting example. Calibration and hardware details are illustrative, with limitations labeled on the page.</p><a href="torsion_control.html">Inspect firmware & plotting ↗</a></article></div></section></main>'''
    home+='''<section class="contact" id="contact"><div class="wrap"><div><p class="eyebrow">06 / Contact</p><h2>Let’s talk engineering.</h2><p>Open to internships, co-ops, and engineering collaborations in mechanical systems, aerospace, robotics, and advanced manufacturing.</p><a href="mailto:hamza.ouriour@gmail.com">hamza.ouriour@gmail.com</a></div><div><p>Boston, Massachusetts<br><a href="tel:+16174078157">617-407-8157</a></p><a href="https://www.linkedin.com/in/hamza-ouriour-659123290/">LinkedIn ↗</a> &nbsp; <a href="https://github.com/Svvipee/Hamza-Ouriour-Portfolio">Portfolio repository ↗</a></div></div></section>'''+footer()
    (ROOT/'index.html').write_text(home,encoding='utf-8')
    for d in projects:
        d['sections']=[section for section in d['sections'] if section[0]!='next']
        content=head(d['title'],d['summary'],'projects/'+d['slug']+'.html','../')+nav('../')
        content+=f'''<main id="main" class="wrap"><div class="case-hero"><a class="breadcrumb" href="../index.html#projects">← All engineering projects</a><p class="eyebrow">{d['kind']}</p><h1>{d['title']}</h1><p class="lead">{d['summary']}</p><dl class="case-meta">'''
        for label,value in [('Role',d['role']),('Organization / team',d['org']),('Date',d['date']),('Tools / methods',d['tools'])]:
            content+=f'<div><dt>{label}</dt><dd>{value}</dd></div>'
        content+='</dl></div>'+metrics(d['metrics'])+'<div class="case-layout"><nav class="case-nav" aria-label="On this page">'
        content+=''.join(f'<a href="#{sid}">{title}</a>' for sid,title,body in d['sections'])+'</nav><article class="case-content">'
        content+=''.join(f'<section id="{sid}"><h2>{title}</h2>{body}</section>' for sid,title,body in d['sections'])
        if d['slug']=='lspace':
            content+='<figure><img src="../rover-concept.png" alt="Isometric CAD view of the Team 13 Mars rover chassis and wheels" loading="lazy" width="993" height="619"><figcaption>Team 13 concept render, extracted from Figure 2 on page 10 of the original review. Team artwork; concept stage.</figcaption></figure>'
        source='Team review, PDF pages 1, 6–7, 19–20, 64 and 73; original portfolio narrative.' if d['slug']=='lspace' else 'Latest résumé; original portfolio narrative where identified. Reported results have not been independently reproduced.'
        content+=f'<div class="actions"><a class="button secondary" href="../index.html#projects">← More projects</a><a class="button" href="mailto:hamza.ouriour@gmail.com">Discuss this work ↗</a></div></article></div></main>'+footer('../')
        (ROOT/'projects'/f"{d['slug']}.html").write_text(content,encoding='utf-8')
    paths=['']+['projects/'+d['slug']+'.html' for d in projects]+['project_v6.html','thermo_demo_full.html','torsion_control.html','srr_viewer_fixed.html']
    (ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+BASE+x+'</loc></url>' for x in paths)+'</urlset>',encoding='utf-8')
    print('Generated homepage, 8 case studies, and sitemap.')

def supporting_pages():
    def page(title,desc,path,body):
        text=head(title,desc,path).replace('</head>','<link rel="stylesheet" href="lab.css"></head>')+nav()+'<main class="lab" id="main">'+body+'</main>'+footer()
        (ROOT/path).write_text(text,encoding='utf-8')
    page('V6 engine CAD assembly','SolidWorks assembly practice with original engine renders.','project_v6.html','''<a class="breadcrumb" href="index.html#library">← Project library</a><p class="eyebrow">Mechanical design / CAD practice</p><h1>V6 engine CAD assembly.</h1><p class="lead">A SolidWorks practice assembly exploring component relationships, model organization, clearances, and kinematics.</p><div class="note">CAD practice project. The available artifacts are assembly renders; manufacturing, combustion performance, and physical engine testing are not documented.</div><section class="lab-panel"><h2>Assembly reasoning</h2><p>The original project focused on understanding a complex multi-part assembly and the interaction of its components. Clearance and kinematic relationships are useful design checks, but rendered geometry alone cannot establish tolerance, strength, or operating performance.</p><p><strong>Next evidence:</strong> add an assembly tree, a section view through the cranktrain, and a documented interference or motion study.</p></section><div class="gallery"><figure><img src="engine2.jpeg" alt="Original SolidWorks V6 engine assembly render, first view" loading="lazy"><figcaption>Original project render · assembly view.</figcaption></figure><figure><img src="engine1.jpeg" alt="Original SolidWorks V6 engine assembly render, second view" loading="lazy"><figcaption>Original project render · alternate view.</figcaption></figure></div>''')
    page('Mars mission requirements review','Original 77-page Team 13 L’SPACE concept review.','srr_viewer_fixed.html','''<a class="breadcrumb" href="projects/lspace.html">← Mars rover case study</a><p class="eyebrow">NASA L’SPACE / Team 13</p><h1>Mission requirements review.</h1><p class="lead">The original 77-page team document includes requirements, subsystem architecture, trade studies, interface control, and risk analysis. This is a concept-stage review.</p><div class="actions"><a class="button" href="Team%2013%20SRR.pdf" download>Download review PDF ↓</a><a class="button secondary" href="Team%2013%20SRR.pdf">Open PDF ↗</a></div><div class="lab-panel"><iframe title="Team 13 Mars mission requirements review PDF" src="Team%2013%20SRR.pdf"></iframe><p>If the embedded viewer is unavailable on your device, use the PDF links above.</p></div>''')
    body='''<a class="breadcrumb" href="projects/thermofluids.html">← Thermofluids case study</a><p class="eyebrow">Interactive engineering model</p><h1>Ideal Brayton cycle.</h1><p class="lead">Explore how pressure ratio and specific heat ratio affect ideal thermal efficiency. This demonstration uses constant specific heats, isentropic compression/expansion, and no pressure losses.</p><div class="lab-panel"><form id="cycle-form" novalidate><div class="inputs"><label for="pr">Pressure ratio P₂/P₁<input id="pr" type="number" value="8" min="1.01" step="0.1" required></label><label for="gamma">Specific heat ratio γ<input id="gamma" type="number" value="1.4" min="1.01" max="1.67" step="0.01" required></label><label for="T1">Inlet temperature (K)<input id="T1" type="number" value="300" min="1" step="1" required></label></div><button class="button" style="margin-top:24px" type="submit">Calculate cycle →</button></form><p id="result" role="status" aria-live="polite"></p><canvas id="chart" width="900" height="420" role="img" aria-label="Temperature at four cycle states; numerical temperatures are listed above">State temperatures are listed in the calculation result above.</canvas><p class="evidence">The horizontal axis is cycle state, not entropy. Heat addition uses the retained illustration parameter T₃ = 2.5 T₂; it is not measured turbine data.</p></div><section class="lab-panel"><h2>Model equations</h2><p>T₂ = T₁ rₚ<sup>(γ−1)/γ</sup> &nbsp; · &nbsp; T₃ = 2.5 T₂ &nbsp; · &nbsp; T₄ = T₃ / rₚ<sup>(γ−1)/γ</sup></p><p>η = 1 − 1 / rₚ<sup>(γ−1)/γ</sup></p><details><summary>Inspect the JavaScript implementation</summary><pre id="source-code">'''+E((ROOT/'thermo.js').read_text(encoding='utf-8'))+'''</pre></details><p><a href="thermo.js">Open the source file</a></p></section><script src="thermo.js"></script>'''
    page('Ideal Brayton cycle visualizer','Interactive ideal Brayton efficiency and state-temperature model.','thermo_demo_full.html',body)
    # Preserve both original demo URLs, with a canonical pointing to the primary demo.
    (ROOT/'thermo_demo_themed.html').write_text((ROOT/'thermo_demo_full.html').read_text(encoding='utf-8'),encoding='utf-8')

if __name__=='__main__':
    generate()
    supporting_pages()
